// Estácio_Mundo2/Nível5 - Vamos colocar um framework para acessar um banco/livro-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Injectable } from '@angular/core';
import { Livro } from '../livro';

const baseURL = 'http://localhost:3030/livros';

export interface LivroMongo {
  _id: string;
  codigo: string;
  codEditora: string;
  titulo: string;
  resumo: string;
  autores: string[];
}

@Injectable({
  providedIn: 'root',
})
export class ControleLivrosService {
  constructor() {}

  obterLivros(): Promise<Livro[]> {
    return fetch(baseURL)
      .then((response) => response.json())
      .then((data) =>
        data.data.map((livro: LivroMongo) => ({
          codigo: livro.codigo,
          codEditora: livro.codEditora,
          titulo: livro.titulo,
          resumo: livro.resumo,
          autores: livro.autores,
        }))
      );
  }

  excluir(codigo: string): Promise<boolean> {
    return fetch(`${baseURL}/${codigo}`, { method: 'DELETE' }).then(
      (response) => response.ok
    );
  }

  incluir(livro: Livro): Promise<boolean> {
    const livroMongo: LivroMongo = {
      _id: '',
      codigo: livro.codigo,
      codEditora: livro.codEditora,
      titulo: livro.titulo,
      resumo: livro.resumo,
      autores: livro.autores,
    };

    return fetch(baseURL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(livroMongo),
    }).then((response) => response.ok);
  }
}

<main class="container">
    <h1>Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título</label>
        <input
          type="text"
          class="form-control"
          id="titulo"
          required
          [(ngModel)]="livro.titulo"
          name="titulo"
        />
      </div>
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea
          class="form-control"
          id="resumo"
          rows="3"
          [(ngModel)]="livro.resumo"
          name="resumo"
        ></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora</label>
        <select
          class="form-control"
          id="editora"
          required
          [(ngModel)]="livro.codEditora"
          name="editora"
        >
          <option *ngFor="let editora of Array_Editoras" [value]="editora.codEditora">
            {{ editora.nome }}
          </option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores</label>
        <textarea
          class="form-control"
          id="autores"
          rows="3"
          [(ngModel)]="autoresForm"
          name="autores"
        ></textarea>
      </div>
      <button type="submit" class="btn btn-success">Salvar</button>
      <button type="button" class="btn btn-secondary m-3" (click)="cancelar()">Cancelar</button>
    </form>
  </main>

// Estácio_Mundo2/Nível5 - Vamos colocar um framework para acessar um banco/livro-servidor/clientes/livros-react/src/LivroDados.js
import { useState } from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";
import './App.css';

const controleLivros = new ControleLivro();
const controleEditora = new ControleEditora();

const LivroDados = props => {
  const opcoes = controleEditora.getEditoras();
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0]);
  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };


  const incluir = (event) => {
    event.preventDefault();
    const livro = {
      codigo: 0,
      codEditora: codEditora,
      titulo: titulo,
      resumo: resumo,
      autores: autores.split("\n")
    };
    
    controleLivros.incluir(livro);
    navigate("/");
  };

  return (
    <main class="container">
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className="form-group" >
          <label htmlFor="titulo">Título</label>
          <input id="titulo" className="form-control" type="text" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
        </div>

        <div>
          <label htmlFor="resumo">Resumo</label>
          <textarea id="resumo" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
        </div>

        <div>
          <label htmlFor="editora">Editora</label>
          <select id="editora" className="form-control" value={codEditora} onChange={tratarCombo}>
            {opcoes.map((item) => (
              <option key={item.codEditora} value={item.codEditora}>
                {item.nome}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label htmlFor="autores">Autores</label>
          <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
        </div>
        <button className="btn btn-success" type="submit">Salvar</button>
      </form>
    </main>
  )
}

export default LivroDados;
