// Estácio_Mundo2/Nível3 - Meu Primeiro Framework/livros-react/src/LivroLista.js
import { useState, useEffect } from "react";
import ControleEditora from "./controle/ControleEditora";
import ControleLivro from "./controle/ControleLivros";



const controleEditora = new ControleEditora();
const controleLivros = new ControleLivro();

const LinhaLivro = props => {
  const { livro, excluir } = props;
  const nomeEditora = controleEditora.getNomeEditora;

  return (
    <tr>
      <td>
        <p>{livro.titulo}</p>
        <button type="button" class="btn btn-danger" onClick={() => excluir(livro.codigo)}>Excluir</button>
      </td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora(livro.codEditora)}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
}

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    setLivros(controleLivros.obterLivros());
    setCarregado(true);
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivros.excluir(codigo);
    setCarregado(false);
  }

  return (
    <main class="container">
      <h1>Catálogo de Livros</h1>
      <table className="table table-striped table-hover">
        <thead className="table ">

          <tr>
            <th class="col-sm-2">Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th class="col-sm-2">Autores</th>
          </tr>

        </thead>
        <tbody>
          {livros.map(livro => (
            <LinhaLivro
                key={livro.codigo}
                livro={livro}
                excluir={excluir}
                getNomeEditora={controleEditora.getNomeEditora}
            />
          ))}

        </tbody>
      </table>
    </main>
  )

}

export default LivroLista;

// Estácio_Mundo2/Nível5 - Vamos colocar um framework para acessar um banco/livro-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { LivroMongo } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: LivroMongo[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir(codigo: string): void {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  }

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora);
  }
}
<main class="container">
    <div>
        <h1>Catálogo de Livros</h1>
    </div>
    <table class="table table-striped">
      <thead class="table-dark text-black">
        <tr>
          <th  class="col-sm-2">Título</th>
          <th>Resumo</th>
          <th class="col-sm-2">Autores</th>
          <th class="col-md-1">Editora</th>
        </tr>
      </thead>

      <tbody>
        <tr *ngFor="let livro of livros">
          <td>
            {{ livro.titulo }}
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
          <td>{{ livro.resumo }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
          <td>{{ obterNome(livro.codEditora) }}</td>    
        </tr>
      </tbody>

    </table>
  </main>
